### ISSUE TITLE
some question about evo

### ISSUE THREAD

**Issue by dzxbiubiubiu** [msadowski/ros_web_tutorial#1]
Hi:)
Recently, I am using the evo [https://michaelgrupp.github.io/evo/](url) to evaluate my slam algorithm(cartographer 3d).But I just can plot the trajectory of odom.Fortunately, I find your work in your blog [https://msadowski.github.io/Comparing-SLAM-with-ROS-evo/](url).
But when I run the script [https://github.com/MichaelGrupp/evo/blob/master/contrib/record_tf_as_posestamped_bag.py](url), it doesn't perform well.

![2d_to_3d](https://user-images.githubusercontent.com/56142867/79510690-6193f380-8070-11ea-8a83-989d944f457b.png)
![map_to_foot与odom对比](https://user-images.githubusercontent.com/56142867/79510786-9c962700-8070-11ea-8b1e-6b6909230b78.png)
Could you give me some questions or could you give me your bagfile that I can try it by your data.
Sorry to contact you here, but I can't find your contact information in your blog.
Thanks!
I am looking forward to your reply!

**Comment by msadowski** [comment]
Hi!

Thanks for getting in touch. I just checked and unfortunately I've purged all my bags couple of weeks ago. The bags used for that blog post were also there :(

Can you tell me what are you plotting in your graphs? How did you derive the data?

**Comment by dzxbiubiubiu** [comment]
Hi!
Thank's for your reply and then I will try to describe my work to you as detailed as possible.

Firstly, I build two model rooms with the gazebo and the robot model is the turtlebot3. 
![图片1](https://user-images.githubusercontent.com/56142867/79555669-8a4cd500-80d2-11ea-9f64-985eda1eabc0.png)
![图片2](https://user-images.githubusercontent.com/56142867/79560638-802ed480-80da-11ea-8e76-bbdd5a284011.png)

Secondly, I run the slam algorithm. Like this:` roslaunch slam_lidarr slam.launch slam_methods:=cartographer_vlp16`.Or `roslaunch slam_lidar slam.launch slam_methods:=cartographer` and so on.

Finally, I make the turtlebot3 cruise the room to collect enough data.
`roslaunch omtb_map_extension_plugin automove.launch room_name:=room_z`
 Then I get the rosbag file, it records some topics such that 'odom' /'clock'/'tf'/'tf_static'/'scan'/'imu'/'map'.

Then,I find the evo project. I can plot the trajectory of nav_msgs/Odometry topic.
![room_l](https://user-images.githubusercontent.com/56142867/79562197-3abfd680-80dd-11ea-8d88-94e4505c49e1.png)
![room_z](https://user-images.githubusercontent.com/56142867/79562207-3eebf400-80dd-11ea-8696-619c9e35738f.png)
As you see it works very well. But it is meaningless to just get the odom topic.

And fortunately I found yor work in your blog. Firstly I get the filtered bag like this:
`rosbag filter room_l1.bag bag_filtered_l1.bag "topic == '/clock' or topic == '/robot1/joint_states' or  topic == '/robot1/odom/filtered' or topic == '/scan' or (topic=='/tf' and m.transforms[0].header.frame_id != '/robot1/map') or topic=='/tf_static'"`

Secondly, I run the script [https://github.com/msadowski/ros_web_tutorial/issues/url](url) like this：
![2020-04-17 19-06-08屏幕截图](https://user-images.githubusercontent.com/56142867/79563000-8757e180-80de-11ea-8885-305849d9ed87.png)
![2020-04-17 19-07-43屏幕截图](https://user-images.githubusercontent.com/56142867/79563118-bd956100-80de-11ea-9b97-5900db44401b.png)
And after that I get a bag that record the tf as posestamp.

Finally I merge the two bag by the script which you wrote in your blog.

And then I plot the trajectory of the merge bag by the evo.
![图片3](https://user-images.githubusercontent.com/56142867/79564012-73ad7a80-80e0-11ea-8419-65c2848933aa.png)
![图片4](https://user-images.githubusercontent.com/56142867/79564024-78722e80-80e0-11ea-83db-5e836b3588c9.png)
and the ''base_footprint'' and the ''base link'' are the same thing in my system. So you can thinf of the "base_footprint" as "base_link".You can see the difference between them.
![图片5](https://user-images.githubusercontent.com/56142867/79564566-7eb4da80-80e1-11ea-87dd-a826f2f446aa.png)
![图片6](https://user-images.githubusercontent.com/56142867/79564570-807e9e00-80e1-11ea-891b-5677f2e699ea.png)

And then I run the cartographer 2d slam algorithm to get the different result like this:
![imagez0](https://user-images.githubusercontent.com/56142867/79564823-f551d800-80e1-11ea-8277-2c67a26f4012.png)
![merge_l1](https://user-images.githubusercontent.com/56142867/79564826-f71b9b80-80e1-11ea-88cf-71df9b6e1de1.png)
![z0_rpe](https://user-images.githubusercontent.com/56142867/79564868-0a2e6b80-80e2-11ea-966e-4384fecbe149.png)
You can see the 2d algorithm perform very well and it  has the perfectly coincident trajectory with the odom.

These are all my work. I get a bad result but I can't find the resolution to the question. What puzzles me most is that the 2d algorithm perform very well and the 3d algorithm perform very bad.Though things went to two extremes , I can't resolve it.

I am not sure my steps are right.I am going crazy because of this problem.

Thanks for your anything that can tell me to solve the problem.
I am sorry that I write so much thing to you.Anyway, thanks very much!

I am looking forward to your reply!

**Comment by msadowski** [comment]
If I were you for the time being I would stick to using a single map for now until you are happy with the results, only then I would move to experimenting with other environments etc. I'm not sure how much my insights will help you as the problem is complex but here they are:

* In a perfect world with perfect sensors, even friction etc. odometry can be your source of groundtruth (in reality it will never be because it will always drift). 
* Cartographer is a SLAM package, most SLAM packages I have experience with will use laser scan messages to create a transform between map and odometry
* If you had a perfect odometry (it's quite easy to get that in the sim) and a perfect SLAM package then the transform between map and odometry will be 0 (both in translation and rotation)
* Based on your graphs I assume your odometry is close to groundtruth. You can take a look at the offset between map and odom frames as you are running your SLAM algorithms. If it moves around quite a lot then I think it would mean that your SLAM is not performing too well

One thing you can try out is running the 2D slam with slam_toolbox - I found it much better than Cartographer out of the box.

I'll have some further thinking about your issue and will let you know if I come up with something else. In the mean time I would advise you to use rviz for debugging issue and only if you are happy with everything I would start looking into evo.

**Comment by dzxbiubiubiu** [comment]
Hi , I am so glad to recieve your reply.
In fact, I have recorded the transform between map and odom.
![room_z1_map_to_odom](https://user-images.githubusercontent.com/56142867/79618728-78544c00-813d-11ea-9dce-5900eaa619b8.png)
Unfortunately, the transform isn't 0, and it moves around quite a lot. It also can be see in my tf tree.

**Comment by msadowski** [comment]
OK, then here is what I would do:

You will be looking at something similar to UMBMark: http://www-personal.umich.edu/~johannb/Papers/umbmark.pdf (that's a great read, highly recommend it).

- In rviz set up a square with known dimensions (similar to what you were doing in one of the settings)
- Manually drive the robot along this path. In Rviz set the world frame to odom and visualise the odometry message (change it so that it keeps the last 400 measurements or so)
- After you've driven the square path check if there is any drift in RVIZ. If there is none then you can try to command the robot to go around the path automatically, this should be pretty easy if you have a perfect odometry
- After you are able to drive over a perfect square in odom, make sure you do 3-4 laps with the scanner on (if you run this without mapping then it will be easier to do next steps) - record a bag
- When you are running the above in odom frame, add the scan message to rviz, set the keep parameter to a large number (100-1000). Do you end up in scan messages building a clear nice map?
- After you have a bag it's slam tuning time, create a launch file that will automatically run the bag file, slam node etc. Change SLAM parameters before every experiment and see what works well.

This is how I would go about it. It'll probably take some time to set up but that's what I've been doing for the past couple of years and this method hasn't failed me yet.

Good luck!

**Comment by dzxbiubiubiu** [comment]
Hi, sorry to reply to you so late.
Thanks for your answer to this question. I will try to resolve this question as you say.

Anyway, Thank you for everything!
